= Notes AI KUL 2018-2019
:toc:
:Author: Robin Van den Broeck
:Email: <robin.broeck@gmail.com>

== Introduction
:Date: 25-09-2018

// TODO: defenition of general intelligence
Aims::
* Long term aim: Artificial *general* intelligence +
* Short term aim: voor een taak specefiek

Turing test::
* Inteligentie nodig voor inteligente te waarderen
* Onduidelijkheid kwa spelregels (vb. hoelang mag de jury de test doen: tot de persoon in slaap valt en enkel het machine niet meer verderkan)

Analoog met vliegen:: De mens kan niet vliegen zoals een vogel (*simulatie*), dus moest een andere manier gevonden worden => vliegtuigen (*reproductie*)

== State-space
:Date: 25-09-2018

Bedoeling van een search tree:: Inmens/oneindig veel knopen in een boom -> men wilt zo weinig mogelijk van de boom genereren om toch het juiste pad te vinden.

Controle probleem:: Welke actie bij welke staat gebruiken. Bijvoorbeeld: wat is een goede zet bij schaak?

Decompositie:: Probleem opsplitsen in meerdere deelproblemen. Om dit te kunnen doen moeten paden onafhankelijk van elkaar zijn. Bv.

Branching-factor:: Gemiddelde hoeveelheid kinderen elke knoop heeft. Men wilt deze zo klein mogelijk houden.

Open knoop:: Een knoop waarvan de kinderen nog niet bekend zijn

Expanderen:: Het bereken van de kinderen van een open knoop.
