= Notes AI KUL 2018-2019
:toc:
:Author: Robin Van den Broeck
:Email: <robin.broeck@gmail.com>

== Introduction
:Date: 25-09-2018

// TODO: defenition of general intelligence
Aims::
* Long term aim: Artificial *general* intelligence +
* Short term aim: voor een taak specefiek

Turing test::
* Inteligentie nodig voor inteligente te waarderen
* Onduidelijkheid kwa spelregels (vb. hoelang mag de jury de test doen: tot de persoon in slaap valt en enkel het machine niet meer verderkan)

Analoog met vliegen:: De mens kan niet vliegen zoals een vogel (*simulatie*), dus moest een andere manier gevonden worden => vliegtuigen (*reproductie*)

== State-space
:Date: 25-09-2018

Bedoeling van een search tree:: Inmens/oneindig veel knopen in een boom -> men wilt zo weinig mogelijk van de boom genereren om toch het juiste pad te vinden.

Controle probleem:: Welke actie bij welke staat gebruiken. Bijvoorbeeld: wat is een goede zet bij schaak?

Decompositie:: Probleem opsplitsen in meerdere deelproblemen. Om dit te kunnen doen moeten paden onafhankelijk van elkaar zijn. Bv.

Branching-factor:: Gemiddelde hoeveelheid kinderen elke knoop heeft. Men wilt deze zo klein mogelijk houden.

Open knoop:: Een knoop waarvan de kinderen nog niet bekend zijn

Expanderen:: Het bereken van de kinderen van een open knoop.


== Blind search

=== Iterative
.Complexiteit
|===
| d | memory             | time
| 1 | asciimath:[b x 1]  | asciimath:[b ^ 1]
| 2 | asciimath:[b x 2]  | asciimath:[b ^ 2]
| 3 | asciimath:[b x 3]  | asciimath:[b ^ 3]
| 4 | asciimath:[b x 4]  | asciimath:[b ^ 4]
| m | asciimath:[b x m]  | asciimath:[b ^ m]

asciimath:[`"time" = b^m`]
asciimath:[`"memory" = O(b*m)`]

IMPORTANT: volgende werkt enkel indien b groot is
asciimath:[`O(b^m) = b^1 + b^2 + b^3 + ... + b^(m-1) + b^m`]
