version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Generate files
      - run:
          name: Build adocs
          command: bundle exec asciidoctor -b html5 -D build ai.adoc recht.adoc

      # Deploy it
      - run:
          name: goto right branch
          command: git checkout -f gh-pages
      - run:
          name: Remove useless files
          command: \
            ls | grep -v .git | grep -v build | xargs rm -rf
      - run:
          name: Move files
          command: mv -v build/* .
      - run:
          name: Make the commit
          command: git commit -m "CircleCI docs build"
      - deploy:
          name: Deploy Release to GitHub
          command: git push

workflows:
  version: 2
  default:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
